// 이 파일은 tesla-http-proxy(vehicle-command v0.4.1) 소스에서 추출한 명령 목록입니다.
// 파라미터 이름과 필수 여부는 프록시가 실제로 파싱하는 값과 일치합니다.

export const COMMAND_GROUPS = [
  {
    title: "도어 · 트렁크 · 창문",
    commands: [
      { name: "door_lock", label: "문 잠금", params: [], choices: [] },
      { name: "door_unlock", label: "문 잠금 해제", params: [], choices: [] },
      { name: "actuate_trunk", label: "트렁크/프렁크 열기", params: [{"name": "which_trunk", "type": "문자열", "required": false}], choices: ["front", "rear"] },
      { name: "window_control", label: "창문 열기(환기)/닫기", params: [{"name": "command", "type": "문자열", "required": true}], choices: ["close", "vent"] },
      { name: "charge_port_door_open", label: "충전구 열기", params: [], choices: [] },
      { name: "charge_port_door_close", label: "충전구 닫기", params: [], choices: [] },
      { name: "open_tonneau", label: "적재함 커버 열기 (사이버트럭)", params: [], choices: [] },
      { name: "close_tonneau", label: "적재함 커버 닫기 (사이버트럭)", params: [], choices: [] },
      { name: "stop_tonneau", label: "적재함 커버 정지 (사이버트럭)", params: [], choices: [] },
    ],
  },
  {
    title: "공조 · 시트",
    commands: [
      { name: "auto_conditioning_start", label: "공조 켜기", params: [], choices: [] },
      { name: "auto_conditioning_stop", label: "공조 끄기", params: [], choices: [] },
      { name: "set_temps", label: "운전석/조수석 온도 설정", params: [{"name": "driver_temp", "type": "숫자", "required": false}, {"name": "passenger_temp", "type": "숫자", "required": false}], choices: [] },
      { name: "set_preconditioning_max", label: "최대 예열/예냉", params: [{"name": "on", "type": "참/거짓", "required": true}, {"name": "manual_override", "type": "참/거짓", "required": false}], choices: [] },
      { name: "set_climate_keeper_mode", label: "climate keeper 모드 (반려동물·캠프)", params: [{"name": "climate_keeper_mode", "type": "숫자", "required": true}, {"name": "manual_override", "type": "참/거짓", "required": false}], choices: [] },
      { name: "set_bioweapon_mode", label: "생화학 방어 모드", params: [{"name": "on", "type": "참/거짓", "required": true}, {"name": "manual_override", "type": "참/거짓", "required": true}], choices: [] },
      { name: "set_cabin_overheat_protection", label: "실내 과열 방지", params: [{"name": "on", "type": "참/거짓", "required": true}, {"name": "fan_only", "type": "참/거짓", "required": false}], choices: [] },
      { name: "set_cop_temp", label: "과열 방지 기준 온도", params: [{"name": "cop_temp", "type": "숫자", "required": true}], choices: [] },
      { name: "remote_seat_heater_request", label: "시트 열선", params: [], choices: [] },
      { name: "remote_seat_cooler_request", label: "시트 통풍", params: [], choices: [] },
      { name: "remote_auto_seat_climate_request", label: "시트 자동 온도 조절", params: [], choices: [] },
      { name: "remote_steering_wheel_heater_request", label: "스티어링 휠 열선", params: [{"name": "on", "type": "참/거짓", "required": true}], choices: [] },
    ],
  },
  {
    title: "충전",
    commands: [
      { name: "charge_start", label: "충전 시작", params: [], choices: [] },
      { name: "charge_stop", label: "충전 중지", params: [], choices: [] },
      { name: "set_charge_limit", label: "충전 한도 설정", params: [{"name": "percent", "type": "숫자", "required": true}], choices: [] },
      { name: "set_charging_amps", label: "충전 전류 설정", params: [{"name": "charging_amps", "type": "숫자", "required": true}], choices: [] },
      { name: "charge_max_range", label: "최대 충전 모드", params: [], choices: [] },
      { name: "charge_standard", label: "표준 충전 모드", params: [], choices: [] },
      { name: "set_scheduled_charging", label: "예약 충전", params: [{"name": "enable", "type": "참/거짓", "required": true}], choices: [] },
      { name: "set_scheduled_departure", label: "출발 시각 예약", params: [{"name": "enable", "type": "참/거짓", "required": true}], choices: [] },
      { name: "add_charge_schedule", label: "충전 일정 추가", params: [{"name": "lat", "type": "숫자", "required": true}, {"name": "lon", "type": "숫자", "required": true}, {"name": "start_time", "type": "숫자", "required": false}, {"name": "start_enabled", "type": "참/거짓", "required": true}, {"name": "end_time", "type": "숫자", "required": false}, {"name": "end_enabled", "type": "참/거짓", "required": true}, {"name": "days_of_week", "type": "요일", "required": true}, {"name": "id", "type": "숫자", "required": false}, {"name": "enabled", "type": "참/거짓", "required": true}, {"name": "one_time", "type": "참/거짓", "required": false}], choices: [] },
      { name: "remove_charge_schedule", label: "충전 일정 삭제", params: [{"name": "id", "type": "숫자", "required": true}], choices: [] },
      { name: "add_precondition_schedule", label: "예열 일정 추가", params: [{"name": "lat", "type": "숫자", "required": true}, {"name": "lon", "type": "숫자", "required": true}, {"name": "precondition_time", "type": "숫자", "required": true}, {"name": "one_time", "type": "참/거짓", "required": false}, {"name": "days_of_week", "type": "요일", "required": true}, {"name": "id", "type": "숫자", "required": false}, {"name": "enabled", "type": "참/거짓", "required": true}], choices: [] },
      { name: "remove_precondition_schedule", label: "예열 일정 삭제", params: [{"name": "id", "type": "숫자", "required": true}], choices: [] },
      { name: "set_managed_charge_current_request", label: "관리형 충전 전류", params: [], choices: [] },
      { name: "set_managed_charger_location", label: "관리형 충전 위치", params: [], choices: [] },
      { name: "set_managed_scheduled_charging_time", label: "관리형 예약 충전 시각", params: [], choices: [] },
    ],
  },
  {
    title: "보안 · 접근 제한",
    commands: [
      { name: "set_sentry_mode", label: "감시 모드", params: [{"name": "on", "type": "참/거짓", "required": true}], choices: [] },
      { name: "set_valet_mode", label: "발렛 모드", params: [{"name": "on", "type": "참/거짓", "required": true}, {"name": "password", "type": "문자열", "required": false}], choices: [] },
      { name: "reset_valet_pin", label: "발렛 PIN 초기화", params: [], choices: [] },
      { name: "set_pin_to_drive", label: "주행 PIN 설정", params: [{"name": "on", "type": "참/거짓", "required": true}, {"name": "password", "type": "문자열", "required": false}], choices: [] },
      { name: "reset_pin_to_drive_pin", label: "주행 PIN 초기화", params: [], choices: [] },
      { name: "clear_pin_to_drive_admin", label: "주행 PIN 해제 (관리자)", params: [], choices: [] },
      { name: "speed_limit_activate", label: "속도 제한 켜기", params: [{"name": "pin", "type": "문자열", "required": true}], choices: [] },
      { name: "speed_limit_deactivate", label: "속도 제한 끄기", params: [{"name": "pin", "type": "문자열", "required": true}], choices: [] },
      { name: "speed_limit_set_limit", label: "속도 제한값 설정", params: [{"name": "limit_mph", "type": "숫자", "required": true}], choices: [] },
      { name: "speed_limit_clear_pin", label: "속도 제한 PIN 삭제", params: [{"name": "pin", "type": "문자열", "required": true}], choices: [] },
      { name: "speed_limit_clear_pin_admin", label: "속도 제한 PIN 삭제 (관리자)", params: [], choices: [] },
      { name: "guest_mode", label: "게스트 모드", params: [{"name": "enable", "type": "참/거짓", "required": true}], choices: [] },
    ],
  },
  {
    title: "미디어",
    commands: [
      { name: "media_toggle_playback", label: "재생/일시정지", params: [], choices: [] },
      { name: "media_next_track", label: "다음 곡", params: [], choices: [] },
      { name: "media_prev_track", label: "이전 곡", params: [], choices: [] },
      { name: "media_next_fav", label: "다음 즐겨찾기", params: [], choices: [] },
      { name: "media_prev_fav", label: "이전 즐겨찾기", params: [], choices: [] },
      { name: "media_volume_up", label: "볼륨 올리기", params: [], choices: [] },
      { name: "media_volume_down", label: "볼륨 내리기", params: [], choices: [] },
      { name: "adjust_volume", label: "볼륨 값 지정", params: [{"name": "volume", "type": "숫자", "required": true}], choices: [] },
      { name: "remote_boombox", label: "붐박스 소리 재생", params: [], choices: [] },
    ],
  },
  {
    title: "기타 · 차량 관리",
    commands: [
      { name: "wake_up", label: "차량 깨우기", params: [], choices: [] },
      { name: "flash_lights", label: "전조등 깜빡이기", params: [], choices: [] },
      { name: "honk_horn", label: "경적", params: [], choices: [] },
      { name: "remote_start_drive", label: "원격 주행 활성화", params: [], choices: [] },
      { name: "trigger_homelink", label: "홈링크 (차고문 등)", params: [{"name": "lat", "type": "숫자", "required": true}, {"name": "lon", "type": "숫자", "required": true}], choices: [] },
      { name: "navigation_request", label: "목적지 전송", params: [], choices: [] },
      { name: "set_vehicle_name", label: "차량 이름 변경", params: [{"name": "vehicle_name", "type": "문자열", "required": true}], choices: [] },
      { name: "schedule_software_update", label: "소프트웨어 업데이트 예약", params: [{"name": "offset_sec", "type": "숫자", "required": true}], choices: [] },
      { name: "cancel_software_update", label: "업데이트 예약 취소", params: [], choices: [] },
      { name: "set_low_power_mode", label: "저전력 모드", params: [{"name": "enable", "type": "참/거짓", "required": true}], choices: [] },
      { name: "keep_accessory_power_mode", label: "액세서리 전원 유지", params: [{"name": "enable", "type": "참/거짓", "required": true}], choices: [] },
      { name: "erase_user_data", label: "사용자 데이터 삭제", params: [], choices: [] },
    ],
  },
];

export const COMMAND_COUNT = COMMAND_GROUPS.reduce((n, g) => n + g.commands.length, 0);
